name: mqtt_learning_client
description: A project to learn MQTT interfaces in Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.3
  typed_data: ^1.3.2
  english_words: ^4.0.0
  rxdart: ^0.27.7
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
